name: PR

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: '5.7'
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.2'
      - name: Build
        run: xcodebuild -scheme GetivySDK -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2'
      - name: Run tests
        run: xcodebuild -scheme GetivySDK -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' test
